[project]
name = "backend"
authors = []
description = ""
telemetry = true
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"
[contracts.another-ape]
path = "contracts/another-ape.clar"

[contracts.sip009]
path = "contracts/sip009.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
